--1.How many total orders has UrbanCart received so far?
select count(*) from public.fact_order
select count(*) from public.fact_order where status<> 'Cancelled';
select count(*) from public.fact_order where status= 'Completed';

--2.How many unique customers have placed at least one order

select count(distinct customer_id ) as unique_customer from public.fact_order ;

--3.Which cities generate the highest number of orders

select c.city,count(*)as total_order from public.fact_order as ord
left join public."DimCustomers" as c on ord.customer_id::bigint=c.customer_id
group by 1 order by 2 desc;

--4.What percentage of customers have placed more than one order

with ct as (select customer_id,count(*)as count_order
from fact_order group by 1  having count(*)>1 )
select count(*)/(select count ( distinct customer_id) from fact_order)*100 as percentage from ct ;

--5.What is the monthly trend of total orders over time

SELECT to_char("date"::date, 'Month') AS month_name, COUNT(*) AS total_order
FROM fact_order GROUP BY EXTRACT(MONTH FROM "date"::date), to_char("date"::date, 'Month')
ORDER BY EXTRACT(MONTH FROM "date"::date);


Revenue & Product Performance
--6.What is the total revenue generated by UrbanCart?

with completed_orders as (
		select oi.*,o.status from public.fact_order_items oi
		left join fact_order o on o.order_id=oi. order_id where status='Completed'
        ) ,
individual_rev as (
		select co.*,p.unit_price,co.quantity*p.unit_price as rev from completed_orders co
		left join dim_products p on co.product_id=p.product_id
		)
select sum(rev )as total_revenue from individual_rev;

--consider the completed and pending order.
with completed_orders as (
		select oi.*,o.status from public.fact_order_items oi
		left join fact_order o on o.order_id=oi. order_id where status in ('Completed','Pending')
        ) ,
individual_rev as (
		select co.*,p.unit_price,co.quantity*p.unit_price as rev from completed_orders co
		left join dim_products p on co.product_id=p.product_id
		)
select sum(rev )as total_revenue from individual_rev;

	
--7.Which product categories contribute the most to total revenue?

with completed_orders as (
		select oi.*,o.status from public.fact_order_items oi
		left join fact_order o on o.order_id=oi. order_id where status='Completed'
        ),
unit_rev as( 
		select co.*,p.category,p.unit_price,co.quantity*p.unit_price as rev from completed_orders co
		left join dim_products p on co.product_id=p.product_id 
		)
select category, sum(rev) as total_revenue from unit_rev group by  1 order by 2 desc;

	
--8.Which individual products generate the highest revenue?

with completed_orders as (
		select oi.*,o.status from public.fact_order_items oi
		left join fact_order o on o.order_id=oi. order_id where status='Completed'
        ),
unit_rev as( 
		select co.*,p.product_name,p.category,p.unit_price,co.quantity*p.unit_price as rev
		from completed_orders co
		left join dim_products p on co.product_id=p.product_id 
		)
select product_name, sum(rev) as total_revenue from unit_rev group by  1 order by 2 desc;


--9.What is the average order value (AOV) and Average Basket Size?
--only for completed order 
with completed_orders as (
		select oi.*,o.status from public.fact_order_items oi
		left join fact_order o on o.order_id=oi. order_id where status='Completed'
        ),
unit_rev as( 
		select co.*,p.product_name,p.category,p.unit_price,co.quantity*p.unit_price as rev 
		from completed_orders co
		left join dim_products p on co.product_id=p.product_id )
select  ROUND(SUM(rev) / COUNT(DISTINCT order_id), 0) AS average_order_value,
round(sum(quantity)/count(distinct order_id),1) as average_basket_size from unit_rev;

-- for all order (with pending, and completed order)
with completed_orders as (
		select oi.*,o.status from public.fact_order_items oi
		left join fact_order o on o.order_id=oi. order_id where status IN ('Completed', 'Pending')
        ),
unit_rev as( 
		select co.*,p.product_name,p.category,p.unit_price,co.quantity*p.unit_price as rev 
		from completed_orders co
		left join dim_products p on co.product_id=p.product_id )
select  ROUND(SUM(rev) / COUNT(DISTINCT order_id), 0) AS average_order_value,
round(sum(quantity)/count(distinct order_id),1) as average_basket_size from unit_rev;

--10.Which products are at risk of stock-out due to high sales volume and low inventory
with product_items_order as (
		select oi.*,o.status,o.customer_id from fact_order_items oi 
		left join fact_order o on oi.order_id=o.order_id
		where status ='Completed'
		),
sales_prod as (
		select * from product_items_order pio
		left join dim_products p on pio.product_id=p.product_id 
		),
stock_out_data as (
			select product_name,sum(quantity) as total_sold,
			max(stock) as stock,max(stock)- sum(quantity) as remail_prod,
			ROUND(max(stock) *1.0 /  NULLIF(sum(quantity),0),2) AS stock_to_sales_ratio
			from sales_prod group by 1 order by 4 asc
			)
select *,
case 
when stock_to_sales_ratio < 0.2 then 'Critical'
when stock_to_sales_ratio between 0.2 and 0.5 then 'High'
when stock_to_sales_ratio between 0.5 and 1 then 'Medium'
when stock_to_sales_ratio > 1 then 'Low' 
else null end as risk_of_stockOut
from stock_out_data;

Customer Behavior & Segmentation
--11.Which customers contribute the highest total revenue?

with rev_per_prod as 
			(
			select oi.*,o.status,o.customer_id,c.full_name,p.unit_price,oi.quantity*P.unit_price as rev 
			from fact_order_items oi 
			left Join fact_order o on oi.order_id=o.order_id 
			left join dim_products p on oi.product_id=p.product_id
			left join public."DimCustomers" c on o.customer_id::bigint=c.customer_id
			 where status in ('Completed')
			 )
select customer_id,full_name,sum(rev) as rev from rev_per_prod group by 1,2 order by rev desc;


 --12.What is the average number of products purchased per order?

with completed_orders as (
		select oi.*,o.status from public.fact_order_items oi
		left join fact_order o on o.order_id=oi. order_id
		--where status='Completed'
        ),
	unit_rev as( 
		select co.*,p.product_name,p.category,p.unit_price,co.quantity*p.unit_price as rev 
		from completed_orders co
		left join dim_products p on co.product_id=p.product_id )
select     
round(sum(quantity)/count(distinct order_id),1) as average_basket_size
from unit_rev;

--13.Do male and female customers show different purchasing patterns by category?

 with ct as (
			 SELECT c.gender,COUNT(o.order_id) AS orders_by_gender,
			 SUM(COUNT(o.order_id)) OVER () AS total_orders_all
			FROM fact_order o
			LEFT JOIN public."DimCustomers" c 
			ON o.customer_id::bigint = c.customer_id
			GROUP BY c.gender)
select *,round(orders_by_gender/total_orders_all,2) as percentage from ct;
-- original query 
with ct as (
		select oi.order_id,oi.product_id,oi.quantity,pr.category,ord.customer_id,cu.gender,ord.status 
		from fact_order_items oi
		left join dim_products as pr on oi.product_id=pr.product_id
		left join fact_order as ord on ord.order_id=oi.order_id
		left join public."DimCustomers" as cu on ord.customer_id::bigint=cu.customer_id
		--where ord.status in ('Completed','Pending')
),ct1 as (
select category,
sum(case when gender='Male' then quantity else null end) as Quantity_of_Male,
sum(case when gender='Female' then quantity else null end) as Quantity_of_female
from ct group by category)
select * ,abs(Quantity_of_Male-Quantity_of_female) as diff from ct1 order by diff desc





--14.Which cities have the highest average order value?

with ct as (
			select oi.*,o.customer_id,o.status,c.city from public.fact_order_items oi  
			left join public.fact_order o on oi.order_id=o.order_id
			left Join public."DimCustomers" c on o.customer_id::bigint = c.customer_id
			--where status='Completed'
			),
ct2 as 	(		
			select ct.*,p.unit_price,ct.quantity*p.unit_price as order_value from ct 
			left join public.dim_products p on ct.product_id=p.product_id 
			)
select city,round(sum(order_value)/count(distinct order_id),0) as avg_ord_val 
from ct2 group by 1 order by 2 desc;

--15. How does customer purchasing behavior change over time since account creation?

with ct as (
					select o.*,cu.full_name,cu.created_at::date from fact_order o 
					join public."DimCustomers" cu on o.customer_id::bigint=cu.customer_id
					where cu.created_at is not null
				),
	ct1 as (
					select  customer_id,date_trunc('month',date::date)::date as order_month,
					full_name,date_trunc('month',created_at)::date as first_order,
					created_at from ct)	,
	ct2 as (
					select created_at,customer_id,
                 (EXTRACT(YEAR FROM order_month) - EXTRACT(YEAR FROM first_order)) * 12 +
			    (EXTRACT(MONTH FROM order_month) - EXTRACT(MONTH FROM first_order)) as  date_diff 
				from ct1)
	select created_at,
	count(distinct case when date_diff=0 then customer_id else null end) as month_0,
	count(distinct case when date_diff=1 then customer_id else null end)  as month_1,
	count(distinct case when date_diff=2 then customer_id else null end)as month_2,
	count(distinct case when date_diff=3 then customer_id else null end)as month_3
	from ct2 group by 1;

Payment & Order Flow Insights
--16.Which payment methods are used most frequently?

with ct as (
		 select o.order_id,o.status,p.methods from fact_order  o
		join fact_payments p on o.order_id=p.order_id 
		where status <>'Cancelled'
		)
select methods, count(*) from  ct group by 1;

--17.Is there any relationship between payment method and order status?
with ct as (
		 select o.order_id,o.status,p.methods from fact_order  o
		join fact_payments p on o.order_id=p.order_id 
		)
select 
status,
count(case when methods='Debit Card'then methods else null end ) as Debit_Card,
count(case when methods='COD' then methods else null end ) as COD,
count(case when methods='Credit Card'  then methods else null end ) as Credit_card,
count(case when methods='bKash' then methods else null end ) as bkash,
count(case when methods='Nagad'then methods else null end ) as Nagad
from  ct group by 1;


--18.Do certain cities prefer specific payment methods?
with ct as (
		 select o.order_id,o.status,p.methods,cu.city from fact_order  o
		join fact_payments p on o.order_id=p.order_id 
		left join public."DimCustomers" cu on cu.customer_id=o.customer_id::bigint
		)
select 
city,
count(case when methods='Debit Card'then methods else null end ) as Debit_Card,
count(case when methods='COD' then methods else null end ) as COD,
count(case when methods='Credit Card'  then methods else null end ) as Credit_card,
count(case when methods='bKash' then methods else null end ) as bkash,
count(case when methods='Nagad'then methods else null end ) as Nagad
from  ct group by 1;

--19.Are higher-value orders associated with specific payment methods?

	with ct as (
		select oi.*,p.product_name,o.status,p.unit_price,oi.quantity*p.unit_price as rev 
		from fact_order_items  oi 
		left join fact_order o on oi.order_id=o.order_id
		left join dim_products p on oi.product_id=p.product_id
) , 
ct1 as (select order_id,sum(rev) as order_value from ct   group by 1),
stats as (select 
		max(order_value),min(order_value),stddev(order_value) as std_1,
		avg(order_value) as avg_value
		from ct1 ),
ct2 as (
		select c.* ,case 
			when c.order_value<s.avg_value then 'low_value_order'
			when c.order_value between avg_value and (avg_value+std_1) then 'mediun_value_order'
			else 'high_value_order' end as order_value_cat
		from ct1 c  cross join stats s) ,
ct3 as (select ct2.*,pa.methods from ct2  left join fact_payments pa on ct2.order_id=pa.order_id) 
select methods,
count(case when order_value_cat='high_value_order' then order_id else null end) as high_value_ord,
count(case when order_value_cat='mediun_value_order' then order_id else null end) as medimu_value_ord,
count( case when order_value_cat='low_value_order' then order_id else null end) as low_value_ord
from ct3 group by 1;


--20.What is the average number of items per order by payment method?
with ct as ( 
select oi.* ,pa.methods from fact_order_items oi 
left join fact_payments as pa on pa.order_id=oi.order_id
)
select methods,round( sum(quantity)/count( distinct order_id),2) as avg_items_order 
from ct group by 1;

Advanced Product & Basket Analysis

--21.Which products are most frequently ordered together?
	with ct as(
		select oi1.order_id ,oi1.product_id as product_1,oi2.product_id as product_2 from fact_order_items oi1 
		join fact_order_items oi2 on oi1.order_id=oi2.order_id
		and oi1.product_id<oi2.product_id
		),
ct2 as (
	select product_1,product_2,
	count(*) as order_times from ct 
	group by 1,2 order by 3 desc 
	) 
select product_1,pr1.product_name as product_1_name,
product_2 ,pr2.product_name as product_2_name,order_times from ct2
	left join dim_products as pr1 on ct2.product_1=pr1.product_id
	left join dim_products as pr2 on ct2.product_2=pr2.product_id;
	
--22.Which product pairs appear most often across all orders?
WITH product_pairs AS (
    	SELECT 
        oi1.order_id,oi1.product_id AS product_1,
        oi2.product_id AS product_2 FROM fact_order_items oi1
    	JOIN fact_order_items oi2 ON oi1.order_id = oi2.order_id
        AND oi1.product_id < oi2.product_id  
)
	SELECT 
    pp.product_1,pr1.product_name AS product_1_name,
    pp.product_2,pr2.product_name AS product_2_name,
    COUNT(*) AS order_count  
FROM product_pairs pp
LEFT JOIN dim_products pr1 ON pp.product_1 = pr1.product_id
LEFT JOIN dim_products pr2 ON pp.product_2 = pr2.product_id
GROUP BY pp.product_1, pr1.product_name,pp.product_2, pr2.product_name
ORDER BY order_count DESC
LIMIT 20;  -- top 20 most frequent pairs


--23.Are there product pairs that consistently drive higher order values? 
 with order_pair as (
			 SELECT  oi1.order_id,oi1.product_id AS product_1,oi2.product_id AS product_2
			  FROM fact_order_items oi1 JOIN fact_order_items oi2 
			   ON oi1.order_id = oi2.order_id AND oi1.product_id < oi2.product_id ),
order_pair_qty as 
			(select op.* ,oi_1.quantity as prod_1_qty , 
			oi_2.quantity as prod_2_qty from order_pair op 
			left join fact_order_items oi_1 on op.order_id=oi_1.order_id and op.product_1=oi_1.product_id
			left join fact_order_items oi_2 on op.order_id=oi_2.order_id and op.product_2=oi_2.product_id),
 prod_rev as(select z.*,
			p1.unit_price,p2.unit_price,z.prod_1_qty*p1.unit_price as rev_prod_1,
			z.prod_2_qty*p2.unit_price as rev_prod_2
			from order_pair_qty z
			left join dim_products p1 on z.product_1=p1.product_id
			left join dim_products p2 on z.product_2=p2.product_id),
pair_group_rev as (
			select d.product_1,d.product_2,
			sum(d.rev_prod_1+d.rev_prod_2) as pair_rev from prod_rev d 
			group by 1,2  order by pair_rev desc)
select di1.product_name,di2.product_name,r.pair_rev from pair_group_rev r
left join dim_products di1 on r.product_1=di1.product_id
left join dim_products di2 on r.product_2=di2.product_id;

--24.Which product combinations could be recommended as bundles to increase revenue
-- alternative 2
WITH product_orders AS (
    SELECT product_id, COUNT(DISTINCT order_id) AS product_order_count
    FROM fact_order_items GROUP BY product_id),
pair_stats AS (
    SELECT oi1.product_id AS product_1,oi2.product_id AS product_2,
    COUNT(DISTINCT oi1.order_id) AS pair_orders FROM fact_order_items oi1
    JOIN fact_order_items oi2
    ON oi1.order_id = oi2.order_id AND oi1.product_id < oi2.product_id
    GROUP BY oi1.product_id, oi2.product_id
)
SELECT ps.product_1, d1.product_name AS product_1_name,
    ps.product_2, d2.product_name AS product_2_name,
    ps.pair_orders,
    ps.pair_orders * 1.0 / LEAST(p1.product_order_count, p2.product_order_count) 
	AS bundle_strength FROM pair_stats ps
JOIN product_orders p1 ON ps.product_1 = p1.product_id
JOIN product_orders p2 ON ps.product_2 = p2.product_id
JOIN dim_products d1 ON ps.product_1 = d1.product_id
JOIN dim_products d2 ON ps.product_2 = d2.product_id
WHERE ps.pair_orders >= 15
ORDER BY bundle_strength DESC;


--25.Based on product co-occurrence and customer behavior,
-- which products should UrbanCart promote together to maximize cross-selling opportunities
with order_pair as (
			 SELECT  oi1.order_id,
			  oi1.product_id AS product_1,
			  oi2.product_id AS product_2
			  FROM fact_order_items oi1
			  JOIN fact_order_items oi2 
			   ON oi1.order_id = oi2.order_id
			   AND oi1.product_id < oi2.product_id
			   ),
order_pair_qty as (
			select op.* ,oi_1.quantity as prod_1_qty , 
			oi_2.quantity as prod_2_qty from order_pair op 
			left join fact_order_items oi_1 on op.order_id=oi_1.order_id and op.product_1=oi_1.product_id
			left join fact_order_items oi_2 on op.order_id=oi_2.order_id and op.product_2=oi_2.product_id
),
 prod_rev as(
			select z.*,
			p1.unit_price,p2.unit_price,z.prod_1_qty*p1.unit_price as rev_prod_1,
			z.prod_2_qty*p2.unit_price as rev_prod_2
			from order_pair_qty z
			left join dim_products p1 on z.product_1=p1.product_id
			left join dim_products p2 on z.product_2=p2.product_id
),
pair_group_rev as (
			select d.product_1,d.product_2,
			sum(d.rev_prod_1+d.rev_prod_2) as pair_rev,
			count(* ) order_times from prod_rev d 
			group by 1,2  order by pair_rev
)
select di1.product_name,di2.product_name,r.pair_rev,r.order_times from pair_group_rev r
left join dim_products di1 on r.product_1=di1.product_id
left join dim_products di2 on r.product_2=di2.product_id order by r.pair_rev desc,r.order_times desc;


















